name: "pet-ghb-act"
on:
  push:
    branches: [ ghb-act ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          ./mvnw compile -Dcheckstyle.skip
          ./mvnw test -Dcheckstyle.skip
          ./mvnw package -Dcheckstyle.skip -Dmaven.test.skip
      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: target
      - uses: actions/download-artifact@v3
        with:
          name: target
      - uses: docker/build-push-action@v4
        with:
          push: false
          tags: scpspc.jfrog.io/docker-virtual/ghb-act:latest